# Generated by Django 3.0.5 on 2020-04-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(max_length=40, unique=True)),
                ('stage', models.CharField(default='1', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('birthname', models.CharField(blank=True, max_length=100, verbose_name='Születési név (na nem egyezik)')),
                ('place', models.CharField(max_length=100, verbose_name='Születési hely')),
                ('gender', models.CharField(max_length=100, verbose_name='Nem')),
                ('haircolor', models.CharField(blank=True, max_length=20, verbose_name='Hajszín')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='Saját honlap')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail cím')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Telefonszám')),
                ('marital_status', models.CharField(blank=True, max_length=100, verbose_name='Családi állapot')),
                ('address', models.CharField(max_length=100, verbose_name='Cím')),
                ('picture', models.FileField(upload_to='media/uploads/', verbose_name='Töltsön fel egy képet magáról!')),
            ],
        ),
    ]
